/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const MedicalProfile = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'medicalConditions' : IDL.Vec(IDL.Text),
  'emergencyContact' : IDL.Text,
  'bloodGroup' : IDL.Text,
  'allergies' : IDL.Vec(IDL.Text),
  'currentMedications' : IDL.Vec(IDL.Text),
});
export const MedicalHistory = IDL.Record({
  'updatedBy' : IDL.Text,
  'timestamp' : IDL.Int,
  'changes' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMedicalNote' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFullMedicalProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(MedicalProfile)],
      ['query'],
    ),
  'getMedicalHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MedicalHistory)],
      ['query'],
    ),
  'getMyMedicalProfile' : IDL.Func([], [IDL.Opt(MedicalProfile)], ['query']),
  'getPublicMedicalProfile' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Opt(
          IDL.Record({
            'age' : IDL.Nat,
            'name' : IDL.Text,
            'emergencyContact' : IDL.Text,
            'bloodGroup' : IDL.Text,
            'allergies' : IDL.Vec(IDL.Text),
          })
        ),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProfilesByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, MedicalProfile))],
      ['query'],
    ),
  'updateMedicalProfileForDoctor' : IDL.Func(
      [IDL.Principal, MedicalProfile, IDL.Text],
      [],
      [],
    ),
  'updatePatientProfile' : IDL.Func([MedicalProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const MedicalProfile = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'medicalConditions' : IDL.Vec(IDL.Text),
    'emergencyContact' : IDL.Text,
    'bloodGroup' : IDL.Text,
    'allergies' : IDL.Vec(IDL.Text),
    'currentMedications' : IDL.Vec(IDL.Text),
  });
  const MedicalHistory = IDL.Record({
    'updatedBy' : IDL.Text,
    'timestamp' : IDL.Int,
    'changes' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMedicalNote' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFullMedicalProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(MedicalProfile)],
        ['query'],
      ),
    'getMedicalHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MedicalHistory)],
        ['query'],
      ),
    'getMyMedicalProfile' : IDL.Func([], [IDL.Opt(MedicalProfile)], ['query']),
    'getPublicMedicalProfile' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Opt(
            IDL.Record({
              'age' : IDL.Nat,
              'name' : IDL.Text,
              'emergencyContact' : IDL.Text,
              'bloodGroup' : IDL.Text,
              'allergies' : IDL.Vec(IDL.Text),
            })
          ),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProfilesByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, MedicalProfile))],
        ['query'],
      ),
    'updateMedicalProfileForDoctor' : IDL.Func(
        [IDL.Principal, MedicalProfile, IDL.Text],
        [],
        [],
      ),
    'updatePatientProfile' : IDL.Func([MedicalProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };